### ISSUE TITLE
express deprecated res.send(status, body): Use res.status(status).send(body)

### ISSUE THREAD

**Issue by rimmi21-zz** [rimmi21/visitor-docker-node#1]
Getting the following issue while running the docker-compose file:

```Mon, 20 Dec 2021 12:05:37 GMT express deprecated res.send(status, body): Use res.status(status).send(body) instead at index.js:13:9
node-app_1      | node:_http_server:272
node-app_1      |     throw new ERR_HTTP_INVALID_STATUS_CODE(originalStatusCode);
node-app_1      |     ^
node-app_1      | 
node-app_1      | RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: Number of Visits: 
node-app_1      |     at new NodeError (node:internal/errors:371:5)
node-app_1      |     at ServerResponse.writeHead (node:_http_server:272:11)
node-app_1      |     at ServerResponse._implicitHeader (node:_http_server:263:8)
node-app_1      |     at write_ (node:_http_outgoing:766:9)
node-app_1      |     at ServerResponse.end (node:_http_outgoing:855:5)
node-app_1      |     at ServerResponse.send (/app/node_modules/express/lib/response.js:221:10)
node-app_1      |     at Command.callback (/app/index.js:13:9)
node-app_1      |     at normal_reply (/app/node_modules/redis/index.js:726:21)
node-app_1      |     at RedisClient.return_reply (/app/node_modules/redis/index.js:824:9)
node-app_1      |     at JavascriptRedisParser.returnReply (/app/node_modules/redis/index.js:192:18) {
node-app_1      |   code: 'ERR_HTTP_INVALID_STATUS_CODE'
node-app_1      | }
node-app_1      | 
node-app_1      | Node.js v17.2.0

**Comment by rimmi21-zz** [comment]
I figured out this was happening because, `res.send` cannot send numbers as value, so it needs to be converted to String. Therefore, in the index.js file, on line number:13, I've converted the value `visits` to string. This is the updated syntax:

```res.send(`Number of Visits: ${visits}`);```

**Comment by rimmi21-zz** [comment]
Issue resolved
